name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  e2e-test-multi-bazel:
    name: ${{ matrix.env.TARGET }} / bazel ${{ matrix.bazel-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        bazel-version: ["6.x", "7.x"]
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            env:
              TARGET: "x86_64-unknown-linux"
          - os: ubuntu-latest
            env:
              TARGET: "aarch64-unknown-linux"
          - os: macos-latest
            env:
              TARGET: "x86_64-apple-darwin"
          - os: macos-latest
            env:
              TARGET: "aarch64-apple-darwin"
          - os: windows-latest
            env:
              TARGET: "x86_64-pc-windows"
              OPTS: "--output_user_root=C:/bzl"

    env:
      USE_BAZEL_VERSION: ${{matrix.bazel-version}}

    steps:
      - uses: actions/checkout@v2

      - name: run e2e tests - workspace
        working-directory: e2e/workspace
        run: |
          bazel $OPTS test //...

      - name: run e2e tests - bzlmod
        working-directory: e2e/bzlmod
        run: |
          bazel $OPTS test //...
