name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  multiplatform:
    name: ${{ matrix.dir }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        dir: ["e2e/bzlmod", "e2e/workspace"]
        os: [ubuntu-latest, macos-12, macos-14]
    env:
      USE_BAZEL_VERSION: "7.x"
    steps:
      - uses: actions/checkout@v2
      - name: test - ${{ matrix.dir }}
        working-directory: ${{ matrix.dir }}
        run: bazel test //...

  windows:
    name: root / windows
    runs-on: windows-latest
    env:
      USE_BAZEL_VERSION: "7.x"
    steps:
      - uses: actions/checkout@v2
      - name: windows build
        run: bazel --output_user_root=C:/bzl build //...
