name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  e2e-test-multi-bazel:
    name: E2E - Bazel ${{matrix.bazel-version}}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        bazel-version: ["6.x", "7.x"]

    env:
      USE_BAZEL_VERSION: ${{matrix.bazel-version}}

    steps:
      - uses: actions/checkout@v2

      - name: run e2e tests - workspace
        working-directory: e2e/workspace
        run: |
          bazel test //...

      - name: run e2e tests - bzlmod
        working-directory: e2e/bzlmod
        run: |
          bazel test //...
