name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  windows:
    name: x86_64-pc-windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build examples
        run: |
          bazelisk --output_user_root=C:/bzl build //examples/...
      - name: Bazel backwards compatibility
        run: |
          $Env:USE_BAZEL_VERSION = "6.4.0"
          bazelisk --output_user_root=C:/bzl build //examples/...
